// ─────────────────────────────────────────────
// Props
// ─────────────────────────────────────────────
interface ChallanFooterProps {
  generatedAt: string; // e.g. "26-02-2026, 12:30 PM"
  systemName: string;  // e.g. "E-Learning & Earning Expense Management System"
}

// ─────────────────────────────────────────────
// Component
// ─────────────────────────────────────────────
export default function ChallanFooter({
  generatedAt,
  systemName,
}: ChallanFooterProps) {
  return (
    <div className="text-center space-y-1.5 pt-2 border-t border-dashed border-slate-100">
      <p className="text-[11px] text-slate-500 font-medium">
        This Document is Generated By System. No Need Signature.
      </p>
      <p className="text-[11px] text-slate-400">
        This Document Was Generated On {generatedAt} |{" "}
        <span className="font-medium">{systemName}</span>
      </p>
      <p className="text-[11px] text-slate-400">
        For Any Query Please Contact The Administration Department
      </p>
    </div>
  );
}
